/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nestject API
 * The Nestject API description
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type { CreatePropertyDto } from ".././model";

export const propertiesControllerFindAll = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.get(`/properties`, options);
};

export const getPropertiesControllerFindAllQueryKey = () => {
  return [`/properties`] as const;
};

export const getPropertiesControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof propertiesControllerFindAll>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof propertiesControllerFindAll>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPropertiesControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof propertiesControllerFindAll>>
  > = ({ signal }) => propertiesControllerFindAll({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof propertiesControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PropertiesControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof propertiesControllerFindAll>>
>;
export type PropertiesControllerFindAllQueryError = AxiosError<unknown>;

export function usePropertiesControllerFindAll<
  TData = Awaited<ReturnType<typeof propertiesControllerFindAll>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propertiesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof propertiesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof propertiesControllerFindAll>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePropertiesControllerFindAll<
  TData = Awaited<ReturnType<typeof propertiesControllerFindAll>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propertiesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof propertiesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof propertiesControllerFindAll>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePropertiesControllerFindAll<
  TData = Awaited<ReturnType<typeof propertiesControllerFindAll>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propertiesControllerFindAll>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function usePropertiesControllerFindAll<
  TData = Awaited<ReturnType<typeof propertiesControllerFindAll>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propertiesControllerFindAll>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPropertiesControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const propertiesControllerCreate = (
  createPropertyDto: CreatePropertyDto,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.post(`/properties`, createPropertyDto, options);
};

export const getPropertiesControllerCreateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof propertiesControllerCreate>>,
    TError,
    { data: CreatePropertyDto },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof propertiesControllerCreate>>,
  TError,
  { data: CreatePropertyDto },
  TContext
> => {
  const mutationKey = ["propertiesControllerCreate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof propertiesControllerCreate>>,
    { data: CreatePropertyDto }
  > = (props) => {
    const { data } = props ?? {};

    return propertiesControllerCreate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PropertiesControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof propertiesControllerCreate>>
>;
export type PropertiesControllerCreateMutationBody = CreatePropertyDto;
export type PropertiesControllerCreateMutationError = AxiosError<unknown>;

export const usePropertiesControllerCreate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof propertiesControllerCreate>>,
      TError,
      { data: CreatePropertyDto },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof propertiesControllerCreate>>,
  TError,
  { data: CreatePropertyDto },
  TContext
> => {
  const mutationOptions = getPropertiesControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
