/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nestject API
 * The Nestject API description
 * OpenAPI spec version: 1.0
 */

export interface CreateUserDto {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @minLength 2 */
  name: string;
}
