/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nestject API
 * The Nestject API description
 * OpenAPI spec version: 1.0
 */

export interface CreatePropertyDto {
  /** @minLength 1 */
  code: string;
  /** @minLength 1 */
  name: string;
  address?: string;
}
