/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nestject API
 * The Nestject API description
 * OpenAPI spec version: 1.0
 */

export * from "./createPropertyDto";
export * from "./createUserDto";
